### ISSUE TITLE
Error occur on uploading theme...

### ISSUE THREAD

**Issue by Ahsan8088** [technext/studio#1]
**### Hi @dearsadiq !!!**
When i upload theme the following error occur... now what to do????

**_Broken Themes
Name | Description |
studio-master | Template is missing. Standalone themes need to have a index.php template file. Child themes need to have a Template header in the style.css stylesheet._**

**Comment by arif-kabir** [comment]
Are you trying to upload it on WordPress?

**Comment by Ahsan8088** [comment]
Yes. i am uploading on Wordpress.

**Comment by arif-kabir** [comment]
It is not an WordPress theme so, it will not work on WordPress. It is just a HTML template.

**Comment by Ahsan8088** [comment]
Thanks for your quick and kind response...

Regards...

**Comment by arif-kabir** [comment]
You are welcome
